### ISSUE TITLE
Tracker event update

### ISSUE THREAD

**Issue by raufsamestone** [raufsamestone/audience-engine-beta#6]
Current output for custom
  - [ ] page path also should be here. 
 
```
  {
    audience_id: '63813f1f-3e4c-4e36-bc43-ad0b2434abf7',
    event_type: 'custom',
    event_data: { eventData: 'asdads', eventValue: true },
    is_conversion: false,
    device_type: 'desktop',
    browser: 'firefox 110',
    language: 'en-US',
    screen: '2560 X 1080',
    utm_params: {},
    referrer: '',
    session_id: {},
    timestamp: '2023-02-25T20:20:08.181Z'
  }
```

Current output for **pageview** 
 

- [ ] is Conversion should be set from script
- [ ] pagePath doesn't work

```
  {
    audience_id: '63813f1f-3e4c-4e36-bc43-ad0b2434abf7',
    event_type: 'page_view',
    event_data: {},
    is_conversion: false,
    device_type: 'desktop',
    browser: 'firefox 110',
    language: 'en-US',
    screen: '2560 X 1080',
    utm_params: {},
    referrer: '',
    session_id: {},
    timestamp: '2023-02-25T20:27:44.928Z'
  }
]

```
